info:
    name: "Benjamin Bow Tie"
    description: "Benjamin is a bow tie pattern with four different shape options."
    handle: "benjamin"
    tags:
        - menswear
        - womenswear
        - accessory
        
seamAllowance:
    metric: 0.6
    imperial: 0.25 

languages:
    en: "English"

parts:
    bowTie1: "Bow Tie knot"
    bowTie2: "Bow Tie knot"
    bowTie3: "Bow Tie knot"
    collarBand: "Collar band"

measurements:
        neckCircumference: 394
        
options:
    # Style group
    tipWidth:
        title: "Tip width"
        description: "The width of the wings of the bow tie at the tip."
        group: "style"
        type: measure
        min: 24
        max: 80
        default: 65
        dependsOn: bowStyle
        onlyOn: [1,2,4]
    knotWidth:
        title: "Knot width"
        description: "The width of the bow tie at the knot/middle."
        group: "style"
        type: measure
        min: 24
        max: 40
        default: 30
    bowLength:
        title: "Bow length"
        description: "The length of the wings of the bow tie."
        group: "style"
        type: measure
        min: 100
        max: 140
        default: 120
    bowStyle:
        title: "Bow style"
        description: "The style of the bow"
        group: "style"
        type: "chooseOne"
        options:
            butterfly: "Butterfly"
            diamond: "Diamond"
            squar3: "Square"
            widesquare: "Wide Square"
        default: "diamond"
    endStyle:
        title: "End style"
        description: "The style of the end of the tie"
        group: "style"
        type: "chooseOne"
        options:
            straight: "Straight end"
            pointed: "Pointed end"
            rounded: "Rounded end"
        default: "straight"
        
    # Fit group
    collarEase:
        title: "Collar ease"
        description: "The amount of ease in the collar of your shirts"
        group: "ease"
        type: "measure"
        min: 0
        max: 40
        default: 15
    adjustmentRibbon:
        title: "Adjustment Ribbon"
        description: "Add a ribbon to make the tie adjustable"
        group: "sewing"
        type: "chooseOne"
        options:
            0: "None"
            1: "13Â½\" - 18\""
        default: 0
