info:
    name: "Wahid Waistcoat"
    handle: "wahid"
    description: "Wahid is a classic fitted waistcoat"
    tags:
        - menswear
        - top
        - waistcoat

parts:
    frontBlock: ".Front block"
    backBlock: ".Back block"
    waistcoatFrontBlock: ".Waistcoat front block"
    front: "Front"
    back: "Back"
    frontFacing: "Front facing"
    frontLining: "Front lining"
    pocketWelt: "Pocket welt"
    pocketFacing: "Pocket facing"
    pocketBag: "Pocket bag"
    pocketInterfacing: "Pocket interfacing"

languages:
    en: "English"
    nl: "Nederlands"

measurements:
    acrossBack: 450
    bicepsCircumference: 335
    centerBackNeckToWaist: 480
    chestCircumference: 1080
    naturalWaistToHip: 120
    neckCircumference: 420
    shoulderSlope: 55
    shoulderToShoulder: 470
    hipsCircumference: 950
    naturalWaist: 885

options:
# ease group

    chestEase:
        title: "Chest ease"
        description: "Amount of ease at the chest."
        group: "ease"
        type: "measure"
        min: 0
        max: 160
        default: 20
    waistEase:
        title: "Waist ease"
        description: "Amount of ease at the waist."
        group: "ease"
        type: "measure"
        min: 0
        max: 160
        default: 80
    hipsEase:
        title: "Hips ease"
        description: "Amount of ease at the hips."
        group: "ease"
        type: "measure"
        min: 0
        max: 160
        default: 40

 # fit group
    lengthBonus:
        title: "Lenght bonus"
        description: "Amount by which to lengthen the waistcoat."
        group: "fit"
        type: "measure"
        min:  0
        max:  50
        default: 15
    backScyeDart:
        title: "Back scye dart"
        description: "The amount to take out in a dart at the back of the armhole."
        group: "fit"
        type: "measure"
        min: 0
        max: 15
        default: 5
    frontScyeDart:
        title: "Front scye dart"
        description: "The amount to take out in a dart at the front of the armhole."
        group: "fit"
        type: "measure"
        min: 0
        max: 20
        default: 10
    centerBackDart:
        title: "Center back dart"
        description: "The amount to take out in a dart at the top of the center back."
        group: "fit"
        type: "measure"
        min: 0
        max: 20
        default: 5

 # style group
    frontDrop:
        title: "Neckline drop"
        description: "The amount the front neckline is lowered. Negative values raise the neckline."
        group: "style"
        type: "measure"
        min: -40
        max: 200
        default: 0
    frontStyle:
        title: "Neckline style"
        description: "Whether you want a rounded or classic necline."
        group: "style"
        type: "chooseOne"
        options:
            1: "Classic"
            2: "Rounded"
        default: 1
    hemStyle:
        title: "Hem style"
        description: "Whether you want a rounded or classic hem."
        group: "style"
        type: "chooseOne"
        options:
            1: "Classic"
            2: "Rounded"
        default: 1
    hemRadius:
        title: "Hem radius"
        description: "Radius of the rounded hem. Not relevant if you chose a classic hem."
        group: "style"
        type: "measure"
        min: 0
        max: 100
        default: 60
        dependsOn: "hemStyle"
        onlyOn: 2
    buttons:
        title: "Buttons"
        description: "The number of buttons on the front."
        group: "style"
        type: "chooseOne"
        options:
            4: 4
            5: 5
            6: 6
            7: 7
            8: 8
            9: 9
            10: 10
            11: 11
            12: 12
        default: 6
 
# insets group
    neckInset:
        title: "Neck inset"
        description: "Distance from the neck to the waistcoat neckline at the shoulder seam."
        group: "insets"
        type: "measure"
        min: 0
        max: 35
        default: 20
    shoulderInset:
        title: "Shoulder inset"
        description: "Distance from the shoulder point to the waistcoat armhole at the shoulder seam."
        group: "insets"
        type: "measure"
        min: 0
        max: 45
        default: 20
    backInset:
        title: "Back inset"
        description: "Amount the back armhole is cut deeper into the back panel."
        group: "insets"
        type: "measure"
        min: 15
        max: 55
        default: 25
    frontInset:
        title: "Front inset"
        description: "Amount the front armhole is cut deeper into the front panel."
        group: "insets"
        type: "measure"
        min: 15
        max: 45
        default: 30
