version: 1.10.6
defaults:
    service: draft
    channel: Freesewing
    draftTheme: Basic
    sampleTheme: Sampler
    compareTheme: Compare
    infoTheme: Info
    pattern: TestPattern
    locale: en

services:
    - info
    - draft
    - sample
    - compare

patternNamespaces:
    - Core
    - Beta
    - Docs
    - Templates
    - Tests

themeNamespaces:
    - Core

channelNamespaces:
    - Core

integrations:
    bail: 
        bail_enabled: false
        api: 'https://data.freesewing.org/error'
        origin: 'core.freesewing.org'
