info:
    name:       "Hugo Hoodie"
    description: "Hugo is a hooded jumper with raglan sleeves."
    handle:     "hugo"
    level: 5
    tags:
        - menswear
        - hoodie
        - sweater
        - top
    inMemoryOf:
        name: "Hugo De Cock"
        link: "https://www.instagram.com/p/p6CnG3rpir/"

parts:
    backBlock:      ".Back block"
    frontBlock:     ".Front block"
    sleeveBlock:    ".Sleeve block"
    front:          "Front"
    back:           "Back"
    sleeve:         "Sleeve"
    pocket:         "Pocket"
    pocketFacing:   "Pocket facing"
    hoodSide:       "Hood side"
    hoodCenter:     "Hood center"
    cuff:           "Cuff"
    waistband:      "Waistband"
    neckBinding:    "Neck binding"

languages:
    en: English
    nl: Nederlands
    de: Deutsch
    fr: French

measurements:
    bicepsCircumference: 335
    centerBackNeckToWaist: 480
    chestCircumference: 1080
    naturalWaistToHip: 120
    neckCircumference: 420
    shoulderSlope: 55
    shoulderToShoulder: 470
    hipsCircumference: 950
    shoulderToWrist: 700
    wristCircumference: 190
    headCircumference: 590

options:

# fit group
    chestEase:
        title: "Chest ease"
        description: "The amount of ease at your chest."
        group: "fit"
        type: measure
        min: -40
        max: 160
        default: 60
    bicepsEase:
        title: "Biceps ease"
        description: "The amount of ease at your upper arm. Note that while we try to respect this, fitting the sleeve to the armhole takes precedence over respecting the exact amount of ease."
        group: "fit"
        type: measure
        min: 0
        max: 80
        default: 40
    cuffEase:
        title: "Cuff ease"
        description: "The amount of ease at your wrist."
        group: "fit"
        type: measure
        min: 0
        max: 100
        default: 35
    lengthBonus:
        title: "Length bonus"
        description: "The amount to lengthen the garment. A negative value will shorten it."
        group: "fit"
        type: measure
        min: 0
        max: 180
        default: 60
    sleeveLengthBonus:
        title: "Sleeve length bonus"
        description: "The amount to lengthen the sleeve. A negative value will shorten it."
        group: "fit"
        type: "measure"
        min: -40
        max: 80
        default: 0
    ribbingStretchFactor:
        title: "Ribbing stretch factor"
        description: "Determines the negative ease for the ribbing."
        group: "fit"
        type: percent
        min: 0
        max: 10
        default: 5
    acrossBackFactor:
        title: "Across back factor"
        description: "Controls your across back width as a factor of your shoulder to shoulder measurement."
        group: "advanced"
        type: "percent"
        min: 93
        max: 99
        default: 96

