info:
  name: "Brian Body Block"
  description: "This body block is the basis of many of our mens tops"
  handle: "brian"
  version: "2.0"
  date: 20170303
  author: "Joost De Cock"
  company: "freesewing"
  link: "freesewing.org/pattern/brian"
  tags:
    - menswear
    - top
    - block

parts:
  backBlock: "Back block"
  frontBlock: "Front block"
  sleeveBlock: "Sleeve block"

languages:
    en: "English"
    nl: "Nederlands"
    fr: "French"

measurements:
    acrossBack: 450
    bicepsCircumference: 335
    centerBackNeckToWaist: 480
    chestCircumference: 1080
    naturalWaistToHip: 120
    neckCircumference: 420
    shoulderSlope: 55
    shoulderToShoulder: 470
    hipsCircumference: 950
    sleeveLengthToWrist: 700
    wristCircumference: 190

options:

# fit group
    chestEase:
        title: "Chest ease"
        description: "The amount of ease at your chest"
        group: "fit"
        type: "measure"
        min: -40
        max: 160
        default: 30
    lengthBonus:
        title: "Length bonus"
        description: "Amount to lengthen the body. A negative value will shorten it."
        group: "fit"
        type: "measure"
        min: -40
        max: 120
        default: 0
    sleeveLengthBonus:
        title: "Sleeve length bonus"
        description: "Amount to lengthen the sleeve. A negative value will shorten it."
        group: "fit"
        type: "measure"
        min: -40
        max: 80
        default: 0
    cuffEase:
        title: "Cuff ease"
        description: "The amount of ease at your wrist"
        group: "fit"
        type: "measure"
        min: 0
        max: 100
        default: 45

# advanced group
    armholeDepthFactor:
        title: "Armhole depth factor"
        description: "A factor that influences the depth of the armhole"
        group: "advanced"
        type: "percent"
        min: 50
        max: 65
        default: 60
    sleevecapHeightFactor:
        title: "Sleevecap height factor"
        description: "A factor that influences the height of the sleevecap"
        group: "advanced"
        type: "percent"
        min: 35
        max: 75
        default: 55
