info:
  name: "Brian Body Block"
  description: "Brian is a basic body block for men"
  handle: "brian"
  tags:
    - menswear
    - top
    - block

parts:
  backBlock: "Back block"
  frontBlock: "Front block"
  sleeveBlock: "Sleeve block"

languages:
    en: "English"
    nl: "Nederlands"
    fr: "French"

measurements:
    bicepsCircumference: 335
    centerBackNeckToWaist: 480
    chestCircumference: 1080
    naturalWaistToHip: 120
    neckCircumference: 420
    shoulderSlope: 55
    shoulderToShoulder: 470
    hipsCircumference: 950
    shoulderToWrist: 700
    wristCircumference: 190

options:

# fit group
    chestEase:
        title: "Chest ease"
        description: "The amount of ease at your chest"
        group: "fit"
        type: "measure"
        min: -40
        max: 160
        default: 30
    bicepsEase:
        title: "Biceps ease"
        description: "The amount of ease at your upper arm"
        group: "fit"
        type: "measure"
        min: 30
        max: 80
        default: 50
    cuffEase:
        title: "Cuff ease"
        description: "The amount of ease at your wrist"
        group: "fit"
        type: "measure"
        min: 0
        max: 100
        default: 45
    lengthBonus:
        title: "Length bonus"
        description: "Amount to lengthen the body. A negative value will shorten it."
        group: "fit"
        type: "measure"
        min: -40
        max: 120
        default: 0
    sleeveLengthBonus:
        title: "Sleeve length bonus"
        description: "Amount to lengthen the sleeve. A negative value will shorten it."
        group: "fit"
        type: "measure"
        min: -40
        max: 80
        default: 0

# advanced group
    armholeDepthFactor:
        title: "Armhole depth factor"
        description: "A factor that influences the depth of the armhole"
        group: "advanced"
        type: "percent"
        min: 50
        max: 65
        default: 50
    sleevecapHeightFactor:
        title: "Sleevecap height factor"
        description: "A factor that influences the height of the sleevecap"
        group: "advanced"
        type: "percent"
        min: 35
        max: 75
        default: 55
    acrossBackFactor:
        title: "Across back factor"
        description: "Controls your across back width as a factor of your shoulder to shoulder measurement"
        group: "advanced"
        type: "percent"
        min: 93
        max: 99
        default: 96

