info:
    name: "Theo trousers"
    description: "Theo is the slimline variation of Theodore"
    handle: "theo"
    version: "2.0"
    author: "Joost De Cock"
    email: "joost@decock.org"
    company: "freesewing.org"
    link: "freesewing.org/pattern/theo"
    tags:
        - menswear
        - trousers
        - bottom

parts:
    back: "Back"
    front: "Front"
    waistbandInterfacingLeft: "Waistband interfacing left"
    waistbandInterfacingRight: "Waistband interfacing right"
    waistbandLeft: "Waistband left"
    waistbandRight: "Waistband right"
    waistbandLiningLeft: "Waistband lining left"
    waistbandLiningRight: "Waistband lining right"
    flyPiece: "Fly piece"
    flyShield: "Fly shield"
    sidePiece: "Side piece"
    frontPocketBag: "Front pocket bag"
    backInnerPocketBag: "Back inner pocket bag"
    backOuterPocketBag: "Back outer pocket bag"
    backPocketFacing: "Back pocket facing"
    backPocketInterfacing: "Back pocket interfacing"
    beltLoop: "Belt loop"

languages:
    en: "English"
    nl: "Nederlands"
    de: "Deutsch"

measurements:
    hipsCircumference: 950
    seatCircumference: 1045
    inseam: 910
    seatDepth: 200
options:
    waistbandWidth:
        title: "Waistband width"
        description: "The width of the waistband."
        group: "fit"
        type: "measure"
        min: -10
        max: 60
        default: 40
    backRise:
        title: "Back rise"
        description: "The amount by which to raise the back."
        group: "fit"
        type: "measure"
        min: 0
        max: 60
        default: 40
    lengthBonus:
        title: "Length bonus"
        description: "The amount by which to lengthen the legs. Negative values shorten them."
        group: "fit"
        type: "measure"
        min: -60
        max: 80
        default: 40
