info:
    name: "Penelope Pencil Skirt"
    description: "Penelope is a simple pencil skirt pattern"
    handle: "penelope"
    level: 3
    tags:
        - womenswear
        - skirt

languages:
    en: "English"

parts:
    front: "Front part"
    back: "Back part"
    waistBand: "Waist band"

measurements:
    naturalWaist: 670
    hipsCircumference: 800
    seatCircumference: 920
    naturalWaistToHip: 130
    naturalWaistToSeat: 240
    naturalWaistToKnee: 520


options:
    lengthBonus:
        title: "Length bonus"
        description: The amount to lengthen the garment. A negative value will shorten it.
        group: "style"
        type: "measure"
        min: -100
        max: 100
        default: 0
    hemBonus:
        title: "Hem bonus"
        description: "Additional width at the hem"
        group: "style"
        type: "measure"
        min: -35
        max: 0
        default: 0
    backVent:
        title: "Back vent"
        description: "Vent at the back seam"
        group: "style"
        type: "chooseOne"
        options:
            1: "Yes"
            0: "No"
        default: "0"
    backVentLength:
        title: "Vertical size of the vent"
        description: "Vertical size of the vent"
        group: "style"
        type: "measure"
        min: 50
        max: 900
        default: 200
        dependsOn: backVent
        onlyOn: [1]
    waistBand:
        title: "Waist band"
        description: "Waist Band"
        group: "style"
        type: "chooseOne"
        options:
            no: "No"
            yes: "Yes"
        default: "yes"
    waistBandWidth:
        title: "Waist band height"
        description: "Waist Band height"
        group: "style"
        type: "measure"
        min: 10
        max: 100
        default: 25
        dependsOn: waistBand
        onlyOn: [yes]
    zipperLocation:
        title: "Zipper placement"
        description: "Zipper placement"
        group: "style"
        type: "chooseOne"
        options:
            side: "Side seam"
            back: "Back seam"
        default: "back"
        dependsOn: backVent
        onlyOn: [0]
    nrOfDarts:
        title: "Number of darts"
        description: "Number of darts on each part"
        group: "style"
        type: "chooseOne"
        options:
            2: "2"
            1: "1"
        default: "2"

    # Fit group
    seatEase:
        title: "Seat ease"
        description: "The amount of ease at the largest part of your bum."
        group: "ease"
        type: "measure"
        min: 0
        max: 60
        default: 30
    waistEase:
        title: "Waist ease"
        description: "The amount of ease at your (natural) waist."
        group: "ease"
        type: "measure"
        min: 0
        max: 60
        default: 10
    waistSideSeamRaise:
        title: "Waist Side Seam Raise"
        description: "Raise of the waist at the side seam"
        group: "fit"
        type: "measure"
        min: 0
        max: 45
        default: 0
    backDartDepthFactor:
        title: "Back Dart Depth Factor"
        description: "The Depth of the back dart as a percentage of the Waist to Hip measurement"
        group: "fit"
        type: "percent"
        min: 35
        max: 70
        default: 50
    frontDartDepthFactor:
        title: "Front Dart Depth Factor"
        description: "The Depth of the front dart as a percentage of the Waist to Hip measurement"
        group: "fit"
        type: "percent"
        min: 30
        max: 65
        default: 45
    dartToSideSeamFactor:
        title: "Dart to Side Seam Factor"
        description: "Shifts the intake from the darts to the side seam and visa versa"
        group: "fit"
        type: "percent"
        min: 30
        max: 70
        default: 50
