info:
  name:     "Trayvon Tie"
  description: "Trayvon is a tie that cuts no corners for a professional result."
  handle:   "trayvon"
  level: 3
  tags:
      - accessories

  inMemoryOf:
    name: "Trayvon Martin"
    link: "https://en.wikipedia.org/wiki/Trayvon_Martin"

parts:
  interfacingTip:   "Interfacing tip"
  interfacingTail:  "Interfacing tail"
  fabricTip:        "Fabric tip"
  fabricTail:       "Fabric tail"
  liningTip:        "Lining tip"
  liningTail:       "Lining tail"
  loop:             "Loop"

languages:
    en: English
    nl: Nederlands
    fr: French

measurements:
    centerBackNeckToWaist: 480
    neckCircumference: 420

options:
    tipWidth:
        title: "Tip width"
        description: "The width of the tie at the tip."
        group: "style"
        type: measure
        min: 20
        max: 120
        default: 60
    knotWidth:
        title: "Knot width"
        description: "The width of the tie at the knot/middle."
        group: "style"
        type: measure
        min: 20
        max: 70
        default: 35

