info:
    name: "Aaron A-Shirt"
    description: "Aaron is an athletic shirt or tank top."
    handle: "aaron"
    inMemoryOf:
        name: "Aaron Swartz"
        link: "https://en.wikipedia.org/wiki/Aaron_Swartz"

parts:
    frontBlock: ".Front block"
    backBlock: ".Back block"
    front: "Front"
    back: "Back"

languages:
    en: "English"
    nl: "Nederlands"
    de: "Deutsch"
    fr: "French"

measurements:
    bicepsCircumference: 335
    centerBackNeckToWaist: 480
    chestCircumference: 1080
    naturalWaistToHip: 120
    neckCircumference: 420
    shoulderToShoulder: 470
    shoulderSlope: 40
    hipsCircumference: 950

options:

# fit group
    chestEase:
        title: "Chest ease"
        description: "The amount of ease at your chest."
        group: "fit"
        type: "measure"
        min: -40
        max: 160
        default: 30
    hipsEase:
        title: "Hips ease"
        description: "The amount of ease at your hips."
        group: "fit"
        type: "measure"
        min: -40
        max: 160
        default: 60
    stretchFactor:
        title: "Stretch"
        description: "Determines the horizontal negative ease."
        group: "fit"
        type: "percent"
        min: 0
        max: 30
        default: 0

# style group
    necklineBend:
        title: "Neckline shape"
        description: "Determines the shape/bend of the neckline at the front."
        group: "style"
        type: "percent"
        min: 5
        max: 95
        default: 95
    necklineDrop:
        title: "Neckline drop"
        description: "The amount the neck is cutout at the front."
        group: "style"
        type: "measure"
        min: 40
        max: 200
        default: 120
    backlineBend:
        title: "Back armhole shape"
        description: "Determines the shape/bend of the back of the armholes."
        group: "style"
        type: "percent"
        default: 30
    armholeDrop:
        title: "Armhole drop"
        description: "Lower the armhole by this amount. Negative values will raise it."
        group: "style"
        type: "measure"
        min: -20
        max: 120
        default: 30
    shoulderStrapWidth:
        title: "Shoulderstrap width"
        description: "The width of the shoulder straps."
        group: "style"
        type: "measure"
        min: 10
        max: 80
        default: 40
    shoulderStrapPlacement:
        title: "Shoulderstrap placement"
        description: "Determines whether the shoulder strap is placed closer to the neck (lower numbers) or the shoulder (higher numbers)."
        group: "style"
        type: "percent"
        min: 20
        max: 80
        default: 45
    lengthBonus:
        title: "Length bonus"
        description: "The amount to lengthen the garment. A negative value will shorten it."
        group: "style"
        type: "measure"
        min: -60
        max: 200
        default: 60
