info:
    name: "Carlton Coat"
    description: "For Sherlock Holmes cosplay, or just a really nice coat"
    handle: "carlton"
    version: "1.0"
    date: 20170203
    author: "Joost De Cock"
    email: "joost@decock.org"
    company: "freesewing.org"
    tags:
        - menswear
        - coat

parts:
  backBlock: ".Back block"
  frontBlock: ".Front block"
  sleeveBlock: ".Sleeve block"
  topsleeveBlock: ".Topsleeve block"
  undersleeveBlock: ".Undersleeve block"
  front: "Front"
  back: "Back"
  tail: "Tail"
  topsleeve: "Topsleeve"
  undersleeve: "Undersleeve"
  belt: "Belt"
  collarStand: "Collar stand"
  collar: "Collar"
  cuffFacing: "Cuff facing"
  pocket: "Pocket"
  pocketFlap: "Pocket flap"
  chestPocketWelt: "Chest pocket welt"

languages:
    en: English

measurements:
    acrossBack: 420
    bicepsCircumference: 350
    centerBackNeckToWaist: 560
    chestCircumference: 1060
    naturalWaist: 930
    naturalWaistToFloor: 1310 
    naturalWaistToHip: 150
    naturalWaistToSeat: 280
    neckCircumference: 390
    seatCircumference: 1130
    shoulderToElbow: 380 
    shoulderToShoulder: 470
    shoulderSlope: 55
    shoulderToWrist: 650
    wristCircumference: 180

options:
    chestEase:
        title: "Chest ease"
        description: "The amount of ease at your chest."
        group: "fit"
        type: measure
        min: 180
        max: 320
        default: 240
    waistEase:
        title: "Waist ease"
        description: "The amount of ease at your waist."
        group: "fit"
        type: measure
        min: 80
        max: 220
        default: 100
    seatEase:
        title: "Seat ease"
        description: "The amount of ease at your butt."
        group: "fit"
        type: measure
        min: 180
        max: 320
        default: 240
    bicepsEase:
        title: "Biceps ease"
        description: "The amount of ease at your upper arm."
        group: "fit"
        type: measure
        min: 20
        max: 80
        default: 50
    cuffEase:
        title: "Cuff ease"
        description: "The amount of ease at your wrist."
        group: "fit"
        type: measure
        min: 100
        max: 180
        default: 140
    shoulderEase:
        title: "Shoulder ease"
        description: "The amount of ease at your shoulder. This increases the shoulder to shoulder and across back distance to accomodate what you're wearing under your coat."
        group: "fit"
        type: measure
        min: 0
        max: 20
        default: 10
    sleeveBend:
        title: "Sleeve bend"
        description: "How much do you want the sleeve to be bent at the elbow"
        group: "fit"
        type: "angle"
        min: 0
        max: 20
        default: 10
    sleeveLengthBonus:
        title: "Sleeve length bonus"
        description: "Amount to lengthen the sleeve. A negative value will shorten it."
        group: "fit"
        type: "measure"
        min: 0
        max: 120
        default: 70
    armholeDepthFactor:
        title: "Armhole depth factor"
        description: "Controls the depth of the armhole. Higher values make a deeper armhole."
        group: "advanced"
        type: "percent"
        min: 65
        max: 75
        default: 71
    sleevecapEase:
        title: "Sleevecap ease"
        description: "The amount by which your sleevhead is longer than the armhole."
        group: "advanced"
        type: measure
        min: 0
        max: 35
        default: 17.5
    sleevecapHeightFactor:
        title: "Sleevecap height factor"
        description: "Controls the height of the sleevecap. Higher values make a higher narrower sleevecap."
        group: "advanced"
        type: "percent"
        min: 45
        max: 55
        default: 50
