info:
  name: "Sven Sweatshirt"
  description: "Sven is a straightforward sweater"
  handle: "sven"
  tags:
      - menswear
      - top
      - sweater

parts:
  backBlock: ".Back block"
  frontBlock: ".Front block"
  sleeveBlock: ".Sleeve block"
  back: "Back"
  front: "Front"
  sleeve: "Sleeve"
  hemRibbing: "Hem ribbing"
  sleeveRibbing: "Sleeve ribbing"

languages:
    en: "English"

measurements:
    bicepsCircumference: 335
    centerBackNeckToWaist: 480
    chestCircumference: 1080
    naturalWaist: 885
    naturalWaistToHip: 120
    neckCircumference: 420
    shoulderSlope: 55
    shoulderToShoulder: 470
    hipsCircumference: 950
    shoulderToWrist: 700
    wristCircumference: 190

options:
    chestEase:
        title: "Chest ease"
        description: "The amount of ease at your chest."
        group: "fit"
        type: "measure"
        min: 30
        max: 160
        default: 80
    bicepsEase:
        title: "Biceps ease"
        description: "The amount of ease at your upper arm."
        group: "fit"
        type: "measure"
        min: 40
        max: 120
        default: 80
    cuffEase:
        title: "Cuff ease"
        description: "The amount of ease at your wrist."
        group: "fit"
        type: "measure"
        min: 0
        max: 100
        default: 60
    lengthBonus:
        title: "Length bonus"
        description: "The amount to lengthen the body."
        group: "fit"
        type: "measure"
        min: 0
        max: 220
        default: 120
    sleeveLengthBonus:
        title: "Sleeve length bonus"
        description: "The amount to lengthen the sleeves. Negative values shorten them."
        group: "fit"
        type: "measure"
        min: -40
        max: 80
        default: 60
    ribbing:
        title: "Ribbing"
        description: "Do you want to include ribbing at the arms and hem, or will you apply a classic hem?"
        group: "style"
        type: "chooseOne"
        options:
            0: "Classic hem (No ribbing)"
            1: "Ribbing hem"
        default: 1
    ribbingHeight:
        title: "Ribbing height"
        description: "The height of the ribbing band at the hem and wrists."
        group: "style"
        type: "measure"
        min: 20
        max: 100
        default: 60
        dependsOn: 'ribbing'
        onlyOn: 1
    ribbingStretchFactor:
        title: "Ribbing stretch factor"
        description: "How much you want the ribbing to be stretched."
        group: "style"
        type: "percent"
        min: 0
        max: 30
        default: 15
        dependsOn: 'ribbing'
        onlyOn: 1
    acrossBackFactor:
        title: "Across back factor"
        description: "Constrols your across back width as a factor of your shoulder to shoulder measurement"
        group: "advanced"
        type: "percent"
        min: 93
        max: 99
        default: 96

